/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/health/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Components */
        get: operations["components_api_snoc_health_components_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_snoc_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_snoc_dashboard_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dashboard/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intents */
        get: operations["intents_api_snoc_dashboard_intents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dashboard/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outcomes */
        get: operations["outcomes_api_snoc_dashboard_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dashboard/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_snoc_dashboard_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requests */
        get: operations["requests_api_snoc_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Request Detail */
        get: operations["request_detail_api_snoc_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation Detail */
        get: operations["operation_detail_api_snoc_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manual Review */
        get: operations["manual_review_api_snoc_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/manual-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manual Review */
        get: operations["manual_review_api_snoc_manual_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_snoc_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/model-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Runs */
        get: operations["model_runs_api_snoc_model_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/operations/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation Metrics */
        get: operations["operation_metrics_api_snoc_operations_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/operations/by-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operations By Action */
        get: operations["operations_by_action_api_snoc_operations_by_action_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/operations/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation Errors */
        get: operations["operation_errors_api_snoc_operations_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/operations/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation Latency */
        get: operations["operation_latency_api_snoc_operations_latency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Executive */
        get: operations["dq_executive_api_snoc_dq_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/executive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Executive */
        get: operations["dq_executive_api_snoc_dq_executive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Dimensions */
        get: operations["dq_dimensions_api_snoc_dq_dimensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Tables */
        get: operations["dq_tables_api_snoc_dq_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Sources */
        get: operations["dq_sources_api_snoc_dq_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Columns */
        get: operations["dq_columns_api_snoc_dq_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/dq/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Rules */
        get: operations["dq_rules_api_snoc_dq_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/model/class-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Snapshot */
        get: operations["model_snapshot_api_snoc_model_class_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/model/confusion-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Snapshot */
        get: operations["model_snapshot_api_snoc_model_confusion_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/model/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Snapshot */
        get: operations["model_snapshot_api_snoc_model_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/workflow/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow */
        get: operations["workflow_api_snoc_workflow_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/workflow/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow */
        get: operations["workflow_api_snoc_workflow_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snoc/business-api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Business Health */
        get: operations["business_health_api_snoc_business_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEvent */
        AuditEvent: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Event Type */
            event_type: string;
            /** Request Id */
            request_id: string | null;
            /** Operation Id */
            operation_id: string | null;
            /** State */
            state: string;
            /** Reason */
            reason: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEvent"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /** CategoryCount */
        CategoryCount: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Range */
            range: string;
            /** Data */
            data: components["schemas"]["CategoryCount"][];
        };
        /** ComponentStatus */
        ComponentStatus: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Detail */
            detail?: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** DQColumn */
        DQColumn: {
            /** Table Name */
            table_name: string;
            /** Source Variant */
            source_variant: string | null;
            /** Column Name */
            column_name: string;
            /** Total Rules */
            total_rules: number;
            /** Passed Rules */
            passed_rules: number;
            /** Failed Rules */
            failed_rules: number;
            /** Error Rules */
            error_rules: number;
            /** Total Records Checked */
            total_records_checked: number;
            /** Total Passed Records */
            total_passed_records: number;
            /** Total Failed Records */
            total_failed_records: number;
            /** Column Dq Score */
            column_dq_score: number | null;
        };
        /** DQDimension */
        DQDimension: {
            /** Dimension */
            dimension: string;
            /** Dimension Score */
            dimension_score: number | null;
            /** Total Rules */
            total_rules: number;
            /** Passed Rules */
            passed_rules: number;
            /** Failed Rules */
            failed_rules: number;
            /** Error Rules */
            error_rules: number;
            /** Failed Checks */
            failed_checks: number;
        };
        /** DQExecutive */
        DQExecutive: {
            /** Overall Quality Score */
            overall_quality_score: number | null;
            /** Total Rules */
            total_rules: number;
            /** Passed Rules */
            passed_rules: number;
            /** Failed Rules */
            failed_rules: number;
            /** Error Rules */
            error_rules: number;
            /** Failed Checks */
            failed_checks: number;
            /** Critical Fatal Open Issues */
            critical_fatal_open_issues: number;
            /** Tables Monitored */
            tables_monitored: number;
            /** Last Execution At */
            last_execution_at: string | null;
        };
        /** DQPayload */
        DQPayload: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Data */
            data?: (components["schemas"]["DQDimension"] | components["schemas"]["DQTable"] | components["schemas"]["DQSource"] | components["schemas"]["DQColumn"] | components["schemas"]["DQRule"])[];
        };
        /** DQRule */
        DQRule: {
            /** Run Id */
            run_id: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Project Name */
            project_name: string | null;
            /** Rule Id */
            rule_id: string;
            /** Table Name */
            table_name: string;
            /** Column Name */
            column_name: string | null;
            /** Dimension */
            dimension: string;
            /** Severity */
            severity: string;
            /** Failed Rows */
            failed_rows: number;
            /** Passed Rows */
            passed_rows: number;
            /** Total Rows */
            total_rows: number;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Comparison Score */
            comparison_score: number | null;
            /** Error Message */
            error_message: string | null;
            /** Rule Family Id */
            rule_family_id: string | null;
            /** Source Variant */
            source_variant: string | null;
        };
        /** DQSource */
        DQSource: {
            /** Source Variant */
            source_variant: string;
            /** Source Quality Score */
            source_quality_score?: number | null;
            /**
             * Total Rules
             * @default 0
             */
            total_rules: number;
            /**
             * Passed Rules
             * @default 0
             */
            passed_rules: number;
            /**
             * Failed Rules
             * @default 0
             */
            failed_rules: number;
            /**
             * Error Rules
             * @default 0
             */
            error_rules: number;
            /**
             * Failed Checks
             * @default 0
             */
            failed_checks: number;
        };
        /** DQTable */
        DQTable: {
            /** Table Name */
            table_name: string;
            /** Source Variant */
            source_variant: string | null;
            /** Table Quality Score */
            table_quality_score: number | null;
            /** Total Rules */
            total_rules: number;
            /** Passed Rules */
            passed_rules: number;
            /** Failed Rules */
            failed_rules: number;
            /** Error Rules */
            error_rules: number;
            /** Failed Checks */
            failed_checks: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Range */
            range: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Mode */
            mode: string;
            operational: components["schemas"]["OperationalSummary"];
            data_quality: components["schemas"]["DQExecutive"] | null;
            /** Unavailable Components */
            unavailable_components?: string[];
        };
        /**
         * DateRange
         * @enum {string}
         */
        DateRange: "today" | "week" | "month" | "year" | "custom";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Request Id */
            request_id: string;
            /** Components */
            components?: components["schemas"]["ComponentStatus"][];
        };
        /** ModelSnapshot */
        ModelSnapshot: {
            /** Available */
            available: boolean;
            /** Label */
            label: string;
            /** Reason */
            reason?: string | null;
        };
        /** OperationRow */
        OperationRow: {
            /** Operation Id */
            operation_id: string;
            /** Request Id */
            request_id: string;
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Pdv Code */
            pdv_code: string | null;
            /** Phone */
            phone: string | null;
            /** Current Revision */
            current_revision: number;
            /** Final Decision */
            final_decision: string | null;
            /** Execution Eligible */
            execution_eligible: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OperationalSummary */
        OperationalSummary: {
            /** Total Requests */
            total_requests: number;
            /** Auto Resolved */
            auto_resolved: number;
            /** In Progress */
            in_progress: number;
            /** Manual Review */
            manual_review: number;
            /** Rejected */
            rejected: number;
            /** Failed */
            failed: number;
            /** Average Processing Ms */
            average_processing_ms: number | null;
            /** Readiness Rate */
            readiness_rate: number | null;
        };
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** RecentRequest */
        RecentRequest: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Request Id */
            request_id: string;
            /** Sender Group */
            sender_group: string;
            /** Intent */
            intent: string;
            /** Confidence */
            confidence: number | null;
            /** Pdv Code */
            pdv_code: string | null;
            /** Otp Present */
            otp_present: boolean;
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Validation Error */
            validation_error: string | null;
        };
        /** RecentResponse */
        RecentResponse: {
            /** Range */
            range: string;
            /** Items */
            items: components["schemas"]["RecentRequest"][];
        };
        /** RequestPage */
        RequestPage: {
            /** Items */
            items: components["schemas"]["RequestRow"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /** RequestRow */
        RequestRow: {
            /** Request Id */
            request_id: string;
            /** Public Reference */
            public_reference: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Status */
            status: string;
            /** Request Kind */
            request_kind: string;
            /** Operation Count */
            operation_count: number;
            /** Escalation Reason */
            escalation_reason: string | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Period */
            period: string;
            /** Received */
            received: number;
            /** Auto Resolved */
            auto_resolved: number;
            /** Escalated */
            escalated: number;
            /** Failed */
            failed: number;
            /** Average Processing Ms */
            average_processing_ms: number | null;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Range */
            range: string;
            /** Granularity */
            granularity: string;
            /** Data */
            data: components["schemas"]["TrendPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Mode */
            mode: string;
            /** Stages */
            stages: components["schemas"]["WorkflowStage"][];
        };
        /** WorkflowStage */
        WorkflowStage: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Processed Count */
            processed_count: number | null;
            /** Error Count */
            error_count: number | null;
            /** Average Duration Ms */
            average_duration_ms: number | null;
            /** Last Successful Event */
            last_successful_event: string | null;
            /** Description */
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    components_api_snoc_health_components_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    summary_api_snoc_dashboard_summary_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_snoc_dashboard_trends_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intents_api_snoc_dashboard_intents_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outcomes_api_snoc_dashboard_outcomes_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_api_snoc_dashboard_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requests_api_snoc_requests_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_detail_api_snoc_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_detail_api_snoc_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_review_api_snoc_escalations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_review_api_snoc_manual_review_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_events_api_snoc_audit_events_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_runs_api_snoc_model_runs_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_metrics_api_snoc_operations_metrics_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operations_by_action_api_snoc_operations_by_action_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_errors_api_snoc_operations_errors_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_latency_api_snoc_operations_latency_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["DateRange"];
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dq_executive_api_snoc_dq_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQExecutive"];
                };
            };
        };
    };
    dq_executive_api_snoc_dq_executive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQExecutive"];
                };
            };
        };
    };
    dq_dimensions_api_snoc_dq_dimensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQPayload"];
                };
            };
        };
    };
    dq_tables_api_snoc_dq_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQPayload"];
                };
            };
        };
    };
    dq_sources_api_snoc_dq_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQPayload"];
                };
            };
        };
    };
    dq_columns_api_snoc_dq_columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQPayload"];
                };
            };
        };
    };
    dq_rules_api_snoc_dq_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DQPayload"];
                };
            };
        };
    };
    model_snapshot_api_snoc_model_class_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSnapshot"];
                };
            };
        };
    };
    model_snapshot_api_snoc_model_confusion_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSnapshot"];
                };
            };
        };
    };
    model_snapshot_api_snoc_model_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSnapshot"];
                };
            };
        };
    };
    workflow_api_snoc_workflow_stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
        };
    };
    workflow_api_snoc_workflow_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
        };
    };
    business_health_api_snoc_business_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentStatus"];
                };
            };
        };
    };
}
